"""empty message

Revision ID: b680b5a2885d
Revises: 
Create Date: 2020-05-14 21:54:49.298752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b680b5a2885d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household',
    sa.Column('household_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.SmallInteger(), server_default='0', nullable=True),
    sa.PrimaryKeyConstraint('household_id')
    )
    op.create_table('member',
    sa.Column('member_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nric', sa.CHAR(length=9), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('annual_income', sa.Float(), server_default='0', nullable=False),
    sa.Column('occupation_type', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('marital_status', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('spouse_nric', sa.CHAR(length=9), nullable=True),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('nric')
    )
    op.create_table('household_member',
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.household_id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ),
    sa.PrimaryKeyConstraint('household_id', 'member_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('household_member')
    op.drop_table('member')
    op.drop_table('household')
    # ### end Alembic commands ###
